### ISSUE TITLE
Installation Path

### ISSUE THREAD

**Issue by creamy11** [yoon-gu/tensorflow-tutorial#1]
![foryk](https://cloud.githubusercontent.com/assets/22143967/21710381/8cedc258-d42b-11e6-8d67-1e061dafc7e7.png)

**Comment by creamy11** [comment]
![foryk2](https://cloud.githubusercontent.com/assets/22143967/21710489/6b4e7038-d42c-11e6-99ef-109f9aa2e167.PNG)
Environment Variables

**Comment by creamy11** [comment]
After rebooting, 

![foryk3](https://cloud.githubusercontent.com/assets/22143967/21710568/015d00e4-d42d-11e6-8c70-e5ee2bc73e84.PNG)

**Comment by creamy11** [comment]
![foryk4](https://cloud.githubusercontent.com/assets/22143967/21710608/42136308-d42d-11e6-8ef7-16f823d5053d.PNG)
Finally Done.

**Comment by yoon-gu** [comment]
@creamy11 thank you.
